package com.dienmayxanh.Enum;

public enum Type {
	ERROR, ALERT, SORTING, ALL_LIST, ALL_OF_BRAND, QUANTITY,
	FULL_INFORMATION, ONLY_PROVINCE, NOT_FILL_ADDRESS, NOT_CHOOSE_WARD, UPDATE_ONLY_PROVINCE_SUBMIT_BEFORE, UPDATE_BY_CLICK_ON_BUTTON_CHANGE, UPDATE_BY_CLICK_ON_DROP_BOX_PROVINCE,
	Alert, Message;
}
